### ISSUE TITLE
The profile links in Masthead should be customizable

### ISSUE THREAD

**Issue by motou** [carbon-design-system/ibm-dotcom-library#3854]
## Detailed description

> Describe in detail the issue you're having.
Currently Masthead uses Translation service to get profile menu items and urls. According to the source code, it retrieves the config json at [https://www.ibm.com/common/v18/js/data/jsononly/uken.json](https://www.ibm.com/common/v18/js/data/jsononly/uken.json)

In that json file, unfortunately the login url is still the old one:
https://idaas.iam.ibm.com/idaas/mtfim/sps/authsvc?PolicyId=urn:ibm:security:authentication:asf:basicldapuser&Target={{window.location}}

For the new w3id with openId, it should be
https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/authorize?response_type=token&client_id=v18loginprod&state={{window.location}}&redirect_uri=https://myibm.ibm.com/OIDCHandler.html&scope=openid&nonce=8675309

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
a bug. If the profile links prop can be customizable, then it could be a feature.

> Is this issue related to a specific component?
Masthead

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I've tried to set up another translation host using the env variable `process.env.TRANSLATION_HOST`, but without success.

> What browser are you working in?
Chrome

> What version of the IBM.com Library are you using?
1.10.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Storage Digital Platform

## Steps to reproduce the issue

1. Step one: open https://www.ibm.com/it-infrastructure/storage/flash/offers/uk-en
2. Step two: select the "Log in" menu item in the profile menu

## Additional information

- This issue is a duplicate of the issue (#4118) opened by @shrinandhini2801.  Issue 4118 is consolidated into this issue and closed.
- Notes

**Comment by jeffchew** [comment]
Hi @motou ! We actually just made a change in the data source to point to the `login.ibm.com` endpoint this morning. You may need to refresh your browser to see the changes.

However, we are pushing up a fix in `1.10.2` that will dynamically set the `window.location`, which is currently available for testing in `v1.10.2-rc.2`.

cc: @ljcarot @annawen1 @kennylam @larahanlon2

**Comment by motou** [comment]
Hi @jeffchew thanks for the info. Is that version `v1.10.2-rc.2` released and published to npm registry?

**Comment by jeffchew** [comment]
@motou yes, that is correct!

**Comment by RobertaJHahn** [comment]
This is now a Fireline question that will be moved to the next Fireline team member in sprint 20-19, if not resolved in 20-18.

**Comment by RobertaJHahn** [comment]
Since this issue was not closed in sprint 20-19, moving to 20-20 and assigning Raph, who is on Fireline that sprint.

**Comment by ljcarot** [comment]
@jeffchew was this issue resolved with the cors proxy change or is it something else?

**Comment by jeffchew** [comment]
This might be the case. @motou do you still need this feature at all? `CORS_PROXY` recently was announced by our team in slack that it is no longer required.

**Comment by motou** [comment]
@jeffchew that feature should be convenient for testing on different servers. For example, currently since the profile links are not customizable, we cannot test the IBMid related feature on stage server.

**Comment by motou** [comment]
The bug is still there. Example: visit https://www.ibm.com/it-infrastructure/storage/flash/offers/uk-en/contact and click "sign in" from the profile menu, then the page will be redirected to https://www.ibm.com/it-infrastructure/storage/flash/offers/uk-en/ instead of the current page. Maybe issues with the url encoding?

**Comment by jeffchew** [comment]
@motou you can already do that with the `navigation` prop for the `masthead`: http://ibmdotcom-react.mybluemix.net/?path=/docs/components-masthead--default

Just pass in custom navigation data into there and you can modify the profile data. Here is the data file currently getting pulled in, you can modify the `profileMenu` data as part of the JSON data going into `navigation`: https://www.ibm.com/common/v18/js/data/jsononly/usen.json

**Comment by jeffchew** [comment]
@motou I actually just tried it and I came back to https://www.ibm.com/it-infrastructure/storage/flash/offers/uk-en/contact after logging in. Can yo provide any additional details on how you replicated the issue? (browser version, etc)?

**Comment by ljcarot** [comment]
@jeffchew @motou  I tested too and it came back to uk-en/contact page for me.

**Comment by motou** [comment]
I've made a CodeSandBox to use the 'navigation' prop: https://codesandbox.io/s/nifty-meninsky-elsx3?file=/src/App.js
It shows an error message `Warning: Failed prop type: Invalid prop `navigation` of type `object` supplied to `MastheadTopNav`, expected an array.`

**Comment by jeffchew** [comment]
@RaphaelAmadeu @RobertaJHahn this was also opened which now might be a duplicate of this https://github.com/carbon-design-system/ibm-dotcom-library/issues/4118. I know we just upgraded this issue from a `question` to a `feature request` but we might want to consolidate this now.

**Comment by RaphaelAmadeu** [comment]
@jeffchew I think consolidating both now would be the best approach, as they are duplicates. So we can focus on this feature.

**Comment by RobertaJHahn** [comment]
@motou Could you tell us when you need this feature.  We will use this information to schedule the work.

**Comment by RobertaJHahn** [comment]
Information consolidated from issue (#4118)

### The problem
_Startups application is built using react and we are using ibmdotcom and carbon components through out the app. In Masthead , I want to make the app redirect to custom login url when the login dropdown from My profile menu is clicked.

### The solution
_Feature to add custom values to the my profile menu

### Additional information
 _The reason why we need to redirect to custom Url is to store the session cookie based on which the API calls will be handled. 

PS: our app is yet to be hosted so i couldn't share the staging url for your reference. The tentative go live date might fall between next week and a week after ( Not confirmed yet).

**Comment by motou** [comment]
> @motou Could you tell us when you need this feature. We will use this information to schedule the work.

Yes, it is scheduled that we should have a demo on stage to show the possibility to use our own profile endpoints before October 15. The app is planned to go online by the end of October. Thanks for scheduling! @RobertaJHahn

**Comment by ljcarot** [comment]
@motou Could you please schedule a meeting with Roberta, Wonil, Jeff and myself?  We like to have a quick review before a page goes live.    Thanks

**Comment by motou** [comment]
Yes sure, I will organize a slack call to demo the requirement

**Comment by RobertaJHahn** [comment]
I have scheduled the meeting tomorrow morning at 10:00 ET.  It looks like Kenny has finished development.  I have included him in the meeting.

@kennylam
